### ISSUE TITLE
Configuration saved but not effective when opened next time

### ISSUE THREAD

**Issue by ou2356** [melon-masou/MonMouse#1]
Operating System: Windows 11 (64 bit)

I really like the functionality of this program, it allows me to use the extended touchable screen without affecting the positioning of the mouse. This greatly improves my work efficiency, but I encountered a small issue with the configuration. Although it does not affect my use, I have to manually configure it every time I quit and reopen the program.

After setting the mouse switch configuration, I clicked save. At the same time, a "monmouth. yml" configuration file was generated, but after I quited the software and reopened it, I found that the previous configuration had not been restored.
The following is the content of the "monmouth. yml" file that I saved:
```
ui:
  inspect_device_interval_ms: 100
processor:
  merge_unassociated_events_ms: 5
  devices:
  - id: HID\VID_18F8&PID_0F99&MI_00\8&3b8c6e57&0&0000
    locked_in_monitor: false
    switch: true
  shortcuts:
    cur_mouse_lock: ''
    cur_mouse_jump_next: ''

```

If you need me to provide any other information, please feel free to ask. Thank you very much for your hard work!
